# Docker-Compose document
# Ref : https://docs.docker.com/compose/compose-file/

name: ${PROJECT_NAME}

services:
  isa:
    image: ${SRV_IMAGE_NAME}
    container_name: ${SRV_CONTAINER_NAME}
    hostname: ${SRV_HOSTNAME}
    ports:
      - ${SRV_PORT}:80
    volumes:
      - ${PROJECT_DIR}/app/api:/usr/local/fastapi
      - ${PROJECT_DIR}/app/cli:/usr/local/isa
      - ${PROJECT_DIR}/app/modules:/usr/local/app
      - ${PROJECT_DIR}/test:/test
      - ${PROJECT_DIR}/cache/develop/data:/var/local/app
      - ${PROJECT_DIR}/conf/docker/docker-compose-dev.yml:/var/local/infra/docker-compose.yml
      - ${PROJECT_DIR}/cache/docker-compose-dev.env:/var/local/infra/docker-compose.env
      - "//var/run/docker.sock:/var/run/docker.sock"
    working_dir: /test
    networks:
      - srv-network

  nginx:
    image: nginx
    container_name: ${SRV_CONTAINER_NAME}-nginx
    ports:
      - 8081:80
    networks:
      - srv-network

networks:
  srv-network:
    driver: bridge
    name: ${INFRA_DOCKER_NETWORK}
    external: true
